### ISSUE TITLE
Double jumping works, wall jumping does not

### ISSUE THREAD

**Issue by Nataly171** [dangbroitsdon/Wall-Jump-Unofficial#16]
With the latest version (v1.5.0) I have both double jumping and wall jumping enabled in the config. The double jump works fine, but I can't wall jump anymore. I'll attach the log file in case that helps.
[latest.log](https://github.com/dangbroitsdon/Wall-Jump-Unofficial/files/9329584/latest.log)

**Comment by dangbroitsdon** [comment]
this be fixed in v1.5.1, i assume you are on singleplayer?

**Comment by Nataly171** [comment]
Yep, singleplayer. Thank you!

**Comment by dangbroitsdon** [comment]
is fixed now (sorry for the long wait, gradle hates me)
