### ISSUE TITLE
Block blacklist doesn't seem to be working

### ISSUE THREAD

**Issue by Anddrond** [dangbroitsdon/Wall-Jump-Unofficial#20]
Just title pretty much, no matter what I do I can still wall jump off the block I put in the config
I've tried the following formats in the confg:
		"block:minecraft:cobblestone",
		"<block:minecraft:cobblestone>"
And also a tag just out of curiosity: 
		"<tag:blocks:forge:cobblestone/normal>"
On 1.18.2, Forge 40.1.73, mod version 1.5.1

**Comment by dangbroitsdon** [comment]
try just cobblestone

**Comment by Anddrond** [comment]
That works thank you, sorry to bother for something so simple
