### ISSUE TITLE
Wall jump enchant bug (1.18.2, Forge 40.1.74)

### ISSUE THREAD

**Issue by ConnixTV** [dangbroitsdon/Wall-Jump-Unofficial#21]
Disabling wall jump doesn't automatically enable the enchant like the setting says it will. Enabling the enchant setting causes the mod to refuse to load.

![Screenshot 2022-08-30 113935](https://user-images.githubusercontent.com/97262402/187517109-a243fc3b-fe1d-4763-987e-6aee5cd6bffd.png)

**Comment by dangbroitsdon** [comment]
there is another option that allows the enchantment toggle so both the enchantment toggle has to be enabled and the ability toggle disabled, but if that's the case then I'll look into it when my pc is fixed which I have no clue when will be

**Comment by ConnixTV** [comment]
Yes, I have the enchant toggle enabled. I think it's a bug with the newer Forge versions, but I can't roll back my forge version because I need the latest version for other mods

**Comment by dangbroitsdon** [comment]
It could be but idk

**Comment by dangbroitsdon** [comment]
figured out what was causing this releasing fix soon
