### ISSUE TITLE
step assist

### ISSUE THREAD

**Issue by closeshot** [dangbroitsdon/Wall-Jump-Unofficial#22]
When enabled step assist does not work. 

Enable/Disable the option doesn't fix it and player won't step up to next block.  

Also after a restart of the game does not fix it.

Everything else works great though.

**Comment by dangbroitsdon** [comment]
what mc version ya on?

**Comment by closeshot** [comment]
MC 1.19.2 
walljump-unofficial-forge-1.5.1.1+1.19-1.19.2

**Comment by dangbroitsdon** [comment]
okay I'll look into it

**Comment by dangbroitsdon** [comment]
could not reproduce;

so try
1. reinstalling the mod
2. reinstalling the instance you are using, i.e. modpack or custom made modpack
preferably the former before the latter but if the former doesn't work then you'll have to resort to it

**Comment by closeshot** [comment]
[modlist.txt](https://github.com/dangbroitsdon/Wall-Jump-Unofficial/files/9547427/modlist.txt)

**Comment by dangbroitsdon** [comment]
yah, i tried all of the mods you had, and i unfortunately couldn't reproduce the mentioned bug, try what i mentioned above
