### ISSUE TITLE
Enchanted books can be applied (via anvil) to any piece of armor, instead of just boots.

### ISSUE THREAD

**Issue by Bluberry-Kat** [dangbroitsdon/Wall-Jump-Unofficial#25]
When the Speed Boost or Double Jump enchants are enabled, an enchanted book can be used to apply these enchantments to any piece of armor.  
This seems to only occur in the anvil. I don't know for sure, but after 20 helmets in an enchanting table, it feels like a safe guess.  

I expect these enchantments to only be considered valid for a pair of boots, as opposed to an entire armor set.  
The enchantments only seem to *do* anything on boots, anyway, and I recall reproducing this in one of the other WallJump forks as well.  

Worth noting I reproduced this in survival mode. Apparently creative mode lets you apply whatever to whatever, without caring.

**Comment by dangbroitsdon** [comment]
is fixed now, ill probably release the update sometime tomorrow, or i will wait. I don't know yet.

**Comment by dangbroitsdon** [comment]
update should be up soon on CF.
