### ISSUE TITLE
(Not really an issue) Double jump enchantment not going on boots

### ISSUE THREAD

**Issue by Mick0604** [dangbroitsdon/Wall-Jump-Unofficial#26]
just wondering where the double jump enchantment goes because it doesnt work on any armor

**Comment by dangbroitsdon** [comment]
It should honestly work on anything including boots, which is a bug that is currently fixed in the latest update I'm working on. Weird, how you aren't able to apply it.

**Comment by dangbroitsdon** [comment]
is fixed now if it was broke idk if it was but should be applicable to boots if not lemme know
