### ISSUE TITLE
Wall-Jump Version 1.6.0-forge+1.16.5 auto-installs Fabric API.

### ISSUE THREAD

**Issue by RobertHDPotatoes** [dangbroitsdon/Wall-Jump-Unofficial#27]
As the title states, using the CurseForge launcher if you installed walljump-unofficial-1.6.0-forge+1.16.5.jar it auto-installs Fabric API, when the Fabric API cannot run on forge.

**Comment by dangbroitsdon** [comment]
just uninstall it, its a byproduct of using architectury, and forgix and not separating the builds into separate modloader files

**Comment by dangbroitsdon** [comment]
I MEAN UHHHHHHHH ITS FIXED HAHAHAHAHAHHAHAHAHAHA
