### ISSUE TITLE
Bug: Wall jumps (when bound to space) don't require re-pressing space to work

### ISSUE THREAD

**Issue by artemisSystem** [dangbroitsdon/Wall-Jump-Unofficial#30]
Not sure how easy this is to fix, but i have an annoyance when using the mod when binding my wall jump button to space (which functions thanks to AMECS, i think).

When i press space and keep holding it, i will cling to walls without needing to re-press space. I'd prefer it if the wall cling would only initiate if i released and held space again after jumping. Maybe it could be a config option.

**Comment by dangbroitsdon** [comment]
ill look into it for the next update.

**Comment by artemisSystem** [comment]
Thanks! Appreaciate it

**Comment by dangbroitsdon** [comment]
is now in the new update. it may be a bit finicky sometimes but should work.

**Comment by artemisSystem** [comment]
Oh, neat!

Btw, what's your stance on supporting 1.19.2? I saw in the commit (here: https://github.com/dangbroitsdon/Wall-Jump-Unofficial/commit/45cf88835713d0dc1f32ab5cddcc5f9d7d956064#diff-e380ecaaf1e9f72be30db395ad3f313674c314672bd1dbdf01362b582475a7cfR35) that you're still supporting 1.19 and up, but this jar crashed when i tried it on 1.19.2, and the file also says 1.19.3. If you don't plan to support 1.19.2, that's understandable, but i would change the line i linked to say 1.19.3 so it gives a version popup instead of crashing.

When that's said, multiple mod authors are considering 1.19.3 to be like a new major version, and since i see you're still supporting 1.18, so i was wondering if you'd consider supporting 1.19.2 on a separate branch?
