### ISSUE TITLE
Broken on 1.19.3

### ISSUE THREAD

**Issue by artemisSystem** [dangbroitsdon/Wall-Jump-Unofficial#32]
I get this when trying to join a *singleplayer* world:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/39034386/206855371-5ab7196c-5546-45cf-aac4-96156fbaff91.png">
https://pastebin.com/mi9R3Rqf

**Comment by dangbroitsdon** [comment]
will release a fix in a min
