### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by artemisSystem** [dangbroitsdon/Wall-Jump-Unofficial#33]
The fabric.mod.json says this mod should support >=1.19, but it does not work on 1.19.2, i get the following crash: https://mclo.gs/CMwKv3F#L196

**Comment by dangbroitsdon** [comment]
it doesnt work in 1.19.2 because 1.19.3 changed where the enchantment registry was held so auto crash because of non existing registry, though i will consider resupporting 1.19.2

**Comment by artemisSystem** [comment]
Then you should change the fabric.mod.json to say >=1.19.3

**Comment by dangbroitsdon** [comment]
hey sometimes you aint gotta and this is one of them times

**Comment by dangbroitsdon** [comment]
jk
