### ISSUE TITLE
Can't sneak

### ISSUE THREAD

**Issue by TheIncgi** [dangbroitsdon/Wall-Jump-Unofficial#34]
With the default setting, I can't sneak since the keybinds overlap.
haven't had this issue with the forge version.

I'm using `walljump-unofficial-1.6.1b-all+1.19.2.jar`

**Comment by dangbroitsdon** [comment]
try enableClassicWallJump in config

**Comment by dangbroitsdon** [comment]
nvm, i just tested it myself and it appears to force a wall jump like in super mario 64 instead of clinging like normally, i'll release a update to fix it.

**Comment by dangbroitsdon** [comment]
nvm should work for you but it doesnt work for 1.19.3 so im gonna release an update for that
