### ISSUE TITLE
Question about v1.6.4

### ISSUE THREAD

**Issue by sternschnaube** [dangbroitsdon/Wall-Jump-Unofficial#36]
Hello, what is the difference between:
**walljump-unofficial-1.6.4-all+1.19.3.jar** and 
**walljump-unofficial-1.6.4-all-networking-removed**?

Thanks already.

**Comment by dangbroitsdon** [comment]
the former is the normal 1.19.3 version, the latter is one without the networking check that prevents people from using it on their friend's servers if it doesn't already have the mod.

**Comment by dangbroitsdon** [comment]
basically a client side only version
